/* Preview catalog keeps the experience useful before API keys are configured. */
window.FinderData = {
  genreMap: {
    12: "Adventure", 14: "Fantasy", 16: "Animation", 18: "Drama", 27: "Horror",
    28: "Action", 35: "Comedy", 36: "History", 37: "Western", 53: "Thriller",
    80: "Crime", 99: "Documentary", 878: "Sci-Fi", 9648: "Mystery",
    10402: "Music", 10749: "Romance", 10751: "Family", 10752: "War",
    10759: "Action", 10762: "Family", 10763: "Documentary", 10764: "Documentary",
    10765: "Sci-Fi", 10766: "Drama", 10767: "Comedy", 10768: "Drama"
  },
  genres: ["All", "Action", "Adventure", "Animation", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Mystery", "Romance", "Sci-Fi", "Thriller"],
  titles: [
    { id: "preview-1", title: "The Glass Horizon", year: 2025, type: "movie", rating: 8.4, genres: ["Sci-Fi", "Drama"], runtime: "2h 08m", overview: "When an astronomer discovers a signal hidden in the light of a distant star, a quiet research mission becomes a search for answers that could reshape life on Earth.", cast: [["Mara Ellis", "Dr. Lena Vale"], ["Jon Bell", "Eli Mercer"], ["R. Kim", "Director"]], providers: ["Netflix", "Prime Video"], tone: "violet", badge: "EDITOR'S PICK" },
    { id: "preview-2", title: "Sunday Best", year: 2025, type: "tv", rating: 8.1, genres: ["Comedy", "Drama"], runtime: "8 episodes", overview: "Three siblings inherit a neighborhood café and discover that keeping it open is easier than agreeing on what comes next.", cast: [["Amara King", "Nia"], ["Theo Grant", "Miles"], ["L. Cooper", "Director"]], providers: ["Hulu", "Apple TV+"], tone: "peach", badge: "NEW SERIES" },
    { id: "preview-3", title: "A Quiet Current", year: 2024, type: "movie", rating: 7.9, genres: ["Drama", "Mystery"], runtime: "1h 54m", overview: "Returning to the coast where she grew up, a marine biologist finds a box of letters that brings an old family mystery into focus.", cast: [["Leah Park", "Iris"], ["Noah Reed", "Sam"], ["J. Flores", "Director"]], providers: ["Max", "Prime Video"], tone: "teal", badge: "CROWD FAVORITE" },
    { id: "preview-4", title: "Night Shift", year: 2025, type: "tv", rating: 8.6, genres: ["Crime", "Thriller"], runtime: "6 episodes", overview: "Over one long night, a city dispatcher and a rookie officer piece together a string of strange calls before sunrise.", cast: [["Milo James", "Cal"], ["Sana Brooks", "Dee"], ["A. Price", "Director"]], providers: ["Netflix", "Max"], tone: "red", badge: "TOP RATED" },
    { id: "preview-5", title: "Wildwood Atlas", year: 2024, type: "movie", rating: 7.7, genres: ["Adventure", "Fantasy"], runtime: "2h 02m", overview: "A cartographer and her younger brother follow a hand-drawn map through a forest that seems to change with every step.", cast: [["Ivy Chen", "June"], ["Caleb Moss", "Robin"], ["S. Avery", "Director"]], providers: ["Disney+", "Hulu"], tone: "green", badge: "FAN FAVORITE" },
    { id: "preview-6", title: "Small Hours", year: 2025, type: "movie", rating: 8.2, genres: ["Romance", "Comedy"], runtime: "1h 47m", overview: "Two strangers share a late-night diner booth and a series of unexpectedly honest conversations about starting over.", cast: [["Elle Monroe", "Kit"], ["Owen Lake", "Ben"], ["N. Wells", "Director"]], providers: ["Prime Video", "Peacock"], tone: "pink", badge: "FEEL-GOOD PICK" },
    { id: "preview-7", title: "Paper Kingdom", year: 2023, type: "tv", rating: 8.8, genres: ["Drama", "Mystery"], runtime: "10 episodes", overview: "An archivist uncovers a hidden history in the margins of a town's oldest books—and a reason someone wants them forgotten.", cast: [["Dara Wells", "Ruth"], ["Ezra Cole", "Theo"], ["P. Laurent", "Director"]], providers: ["Apple TV+", "Max"], tone: "gold", badge: "ACCLAIMED" },
    { id: "preview-8", title: "Deep Blue Days", year: 2024, type: "movie", rating: 7.6, genres: ["Documentary", "Adventure"], runtime: "1h 36m", overview: "A small crew of ocean researchers documents a season of surprising encounters beneath the surface of the Pacific.", cast: [["A. Morgan", "Narrator"], ["M. Soto", "Director"]], providers: ["Disney+", "Prime Video"], tone: "blue", badge: "A TRUE STORY" },
    { id: "preview-9", title: "Last Stop, Tomorrow", year: 2025, type: "tv", rating: 8.0, genres: ["Sci-Fi", "Adventure"], runtime: "7 episodes", overview: "Passengers on a late train wake to find their familiar route has taken them somewhere no map can explain.", cast: [["Niko Vale", "Ash"], ["Tess Rowan", "Mina"], ["D. Frost", "Director"]], providers: ["Netflix", "Apple TV+"], tone: "orange", badge: "JUST ADDED" },
    { id: "preview-10", title: "The Good Company", year: 2023, type: "movie", rating: 7.8, genres: ["Comedy", "Crime"], runtime: "1h 49m", overview: "A pair of mismatched coworkers make one last attempt to save their tiny repair shop from an unusually determined competitor.", cast: [["Max Rivers", "Leon"], ["Gina Hart", "Bea"], ["R. Patel", "Director"]], providers: ["Peacock", "Hulu"], tone: "lime", badge: "LIGHT & CLEVER" }
  ]
};
